apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: payments-wf-
spec:
  entrypoint: main
  templates:
  # MAIN DAG (Directed Acyclic Graph)
  - name: main
    dag:
      tasks:
        - name: fin-schedule
          template: successfully-job
          arguments:
            parameters:
              - name: job
                value: "Fin Schedule"

        - name: liquidation
          dependencies: [fin-schedule]
          template: successfully-job
          arguments:
            parameters:
              - name: job
                value: "Liquidation"

        - name: anticipation
          dependencies: [fin-schedule]
          template: successfully-job
          arguments:
            parameters:
              - name: job
                value: "Anticipation"

        - name: registration
          dependencies: [liquidation, anticipation]
          template: successfully-job
          arguments:
            parameters:
              - name: job
                value: "Registration"

        - name: edi
          dependencies: [liquidation, anticipation]
          template: successfully-job
          arguments:
            parameters:
              - name: job
                value: "EDI"

        - name: accounting
          dependencies: [liquidation, anticipation]
          template: accounting-with-approval

# TEMPLATES
  - name: successfully-job
    inputs:
      parameters:
        - name: job
    container:
      image: rafaelbodao/fakejob:latest
      env:
        - name: SECONDS_TO_SLEEP
          value: "5"

  - name: failed-job
    inputs:
      parameters:
        - name: job
    container:
      image: rafaelbodao/fakejob:latest
      env:
        - name: SECONDS_TO_SLEEP
          value: "5"
        - name: SHOULD_FAIL
          value: "true"

  - name: manual-approval
    suspend:
      duration: "24h" # waits up to 24h for manual approval

  - name: accounting-with-approval
    steps:
      - - name: wait-approval
          template: manual-approval
      - - name: run-accounting
          template: successfully-job
          arguments:
            parameters:
              - name: job
                value: "Accounting"