apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-payments-wf
  namespace: default
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: fin-schedule
            templateRef:
              name: template-successful-job
              template: successful-job
            arguments:
              parameters:
                - name: job
                  value: "Fin Schedule"

          - name: liquidation
            dependencies: [fin-schedule]
            templateRef:
              name: template-successful-job
              template: successful-job
            arguments:
              parameters:
                - name: job
                  value: "Liquidation"

          - name: anticipation
            dependencies: [fin-schedule]
            templateRef:
              name: template-successful-job
              template: successful-job
            arguments:
              parameters:
                - name: job
                  value: "Anticipation"

          - name: registration
            dependencies: [liquidation, anticipation]
            templateRef:
              name: template-successful-job
              template: successful-job
            arguments:
              parameters:
                - name: job
                  value: "Registration"

          - name: edi
            dependencies: [liquidation, anticipation]
            templateRef:
              name: template-successful-job
              template: successful-job
            arguments:
              parameters:
                - name: job
                  value: "EDI"

          - name: accounting
            dependencies: [liquidation, anticipation]
            templateRef:
              name: template-manual-approval
              template: awaiting-approval
            arguments:
              parameters:
                - name: job
                  value: "Accounting"